name: loading in server

on:
  push:
    branches:
      -main

jobs:
  ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.HOSTP }}
          username: ${{ secrets.USERNAMEP }}
          password: ${{ secrets.PASSWORDP }}
          local-dir: ./
          server-dir: /public_html